In [2]:
%matplotlib inline
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import random

In [4]:
Class_A = np.random.randint (100, size = (10,5))
Class_B = np.random.randint (100, size = (10, 5))
Class_C = np.random.randint (100, size = (10,5))

print ("班級A:\n", Class_A)
print ("班級B:\n", Class_B)
print ("班級C:\n", Class_C)

班級A:
 [[94 22 75 12 83]
 [35 33 95  4 97]
 [61  6 48  9 29]
 [41 99 30 13 80]
 [67 58 98 79 37]
 [15 39  1 41 18]
 [46  7  2 93 58]
 [64 80 68 81 80]
 [53 54 81 92  2]
 [ 6 99 20 93 64]]
班級B:
 [[28 94  6 79 55]
 [79 94 74 57 45]
 [ 0 17 54 76 10]
 [22 11 52 22 44]
 [40 37 77 53 35]
 [46 65 77 86 18]
 [72 45 34 28 12]
 [94 34 67 99  7]
 [28 79 84 71 32]
 [67  4 93 81 13]]
班級C:
 [[32 79 57 20 83]
 [ 2 38 70 32 41]
 [10 50 14 93 21]
 [96 76 36 95 68]
 [24 69 97 78  4]
 [74 30 57 56  0]
 [58 88 82 25 60]
 [16 85 27 48 45]
 [ 5 76 93 27 54]
 [ 3 17 32 34 94]]


In [5]:
weight = np.array([0.25, 0.25, 0.25, 0.15, 0.10])

In [6]:
Class_A_sum = np.dot(Class_A, weight)
Class_B_sum = np.dot(Class_B, weight)
Class_C_sum = np.dot(Class_C, weight)

In [8]:
print ("A班加權成績：", Class_A_sum)
print ("B班加權成績：", Class_B_sum)
print ("C班加權成績：", Class_C_sum)

A班加權成績： [57.85 51.05 33.   52.45 71.3  21.7  33.5  73.15 61.   51.6 ]
B班加權成績： [49.35 74.8  30.15 28.95 49.95 61.7  43.15 64.3  61.6  54.45]
C班加權成績： [53.3  36.4  34.55 73.05 59.6  48.65 66.75 43.7  52.95 27.5 ]
