In [2]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# 作業一 拒絕機器人


In [3]:
from numpy.random import choice

In [4]:
import random

In [5]:
words_1 = ["我爸", "我媽", "我哥", "我姐", "我同學", "我表哥"]

In [6]:
words_2= ["答應", "應該", "想要", "需要", "要去", "那天"]

In [7]:
words_3 = ["吃晚餐", "家庭聚餐", "家庭旅遊", "看電影", "打工"]

In [8]:
msg = "怎麼了嗎？"
while (msg !="bye"):
    msg = input ("你找我？")
    if "考試" in msg:
        print ("我都沒念")
    else: 
        RFS = random.choice (words_1)
        RFV = random.choice (words_2)
        RFQ = random.choice (words_3)
        print (RFS, "剛好", RFV, RFQ)

你找我？ 
我同學 剛好 需要 吃晚餐
你找我？ 
我姐 剛好 需要 打工
你找我？bye
我同學 剛好 想要 家庭旅遊


# 作業二 托福考試：45秒要講幾個字

In [9]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [11]:
print ("幾秒鐘的說話時間？")
egg = input (" ")
print (egg, "秒要講", float (egg) * 3, "個字")

幾秒鐘的說話時間？
 34
34 秒要講 102.0 個字


# 作業三 計算全班加權平均數


In [17]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from random import *

In [18]:
A_grades = np.random.randint(100, size = (10, 5))
B_grades = np.random.randint(100, size = (10, 5))
C_grades = np.random.randint(100, size = (10, 5))

In [19]:
weights = [0.25, 0.25, 0.25, 0.15, 0.10]

In [20]:
print ("A班:\n", A_grades, "\n")
print ("B班:\n", B_grades, "\n")
print ("C班:\n", C_grades, "\n")

A班:
 [[90 83  0 45 90]
 [42 87 45 41 97]
 [ 4 52  7 82 58]
 [35 11 11 61 86]
 [57 67 73 65 60]
 [39 70 62 71 62]
 [90 32 96 31 75]
 [28 59 49 16 19]
 [44  6 75 43 40]
 [38 92 85 14 73]] 

B班:
 [[35 60 96 96 70]
 [43 98  3 66 20]
 [78  0 65  8 41]
 [ 7 92 33 17 10]
 [79 15 46 61 38]
 [92 33 51  8 68]
 [ 1 29 67 54 78]
 [68 33 45 89 57]
 [94 37 25 14 19]
 [56 51 64 68 20]] 

C班:
 [[83 35  1 87 81]
 [84 26  0 89 77]
 [65 72 97 24 29]
 [66 14 22 61 89]
 [35 60 94 79 64]
 [27 43 94 25  5]
 [54 27 17 15 56]
 [18 34 63 91 62]
 [18 28  4 82 44]
 [22 12  9 93  5]] 



In [21]:
TA = np.dot(A_grades, weights)
TB = np.dot(B_grades, weights)
TC = np.dot(C_grades, weights)

In [24]:
print ("A班分數:\n", TA, "\n")
print ("B班分數:\n", TB, "\n")
print ("C班分數:\n", TC, "\n")

A班分數:
 [59.   59.35 33.85 32.   65.   59.6  66.65 38.3  41.7  63.15] 

B班分數:
 [69.15 47.9  41.05 36.55 47.95 52.   40.15 55.55 43.   54.95] 

C班分數:
 [50.9  48.55 65.   43.55 65.5  45.25 32.35 48.6  29.2  25.2 ] 

